/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rcc.tech;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false); 
        btnStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblLink = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblPort = new javax.swing.JTextField();
        lblPassword = new javax.swing.JPasswordField();
        btnStart = new javax.swing.JButton();
        btnStop = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();
        btnStart1 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        stu_ID = new javax.swing.JTextField();
        stu_Name = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        stu_AL_main = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        stu_AL_first = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        stu_AL_secound = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        stu_OL_Mathematics = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        stu_OL_Science = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        stu_OL_Sinhala = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        stu_OL_Religion = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        stu_OL_History = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        stu_OL_English = new javax.swing.JComboBox<>();
        bkt1_name = new javax.swing.JComboBox<>();
        stu_OL_BKT1 = new javax.swing.JComboBox<>();
        bkt2_name = new javax.swing.JComboBox<>();
        stu_OL_BKT2 = new javax.swing.JComboBox<>();
        bkt3_name = new javax.swing.JComboBox<>();
        stu_OL_BKT3 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rcc.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel2.setText("RCC - TECH Student Data Management System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(227, 255, 255));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rcc.jpeg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Corbel", 0, 24)); // NOI18N
        jLabel4.setText("Login To Database");

        lblLink.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblLink.setText("jdbc:mysql://localhost");

        jLabel5.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel5.setText("Link / port");

        jLabel6.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel6.setText("User Name");

        lblUser.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblUser.setText("root");

        jLabel7.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        jLabel7.setText("Password");

        lblPort.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        lblPort.setText("3306");

        lblPassword.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N

        btnStart.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnStop.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnStart1.setFont(new java.awt.Font("Corbel", 0, 20)); // NOI18N
        btnStart1.setText("Connect");
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblLink, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPort, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(255, 255, 255))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnStart1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStart)
                                .addGap(44, 44, 44)
                                .addComponent(btnStop))
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart)
                            .addComponent(btnStop)
                            .addComponent(btnStart1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", jPanel3);

        jLabel23.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel23.setText("Index Number");

        stu_ID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stu_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_IDActionPerformed(evt);
            }
        });

        stu_Name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel24.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel24.setText("Name");

        jLabel25.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel25.setText("Main Subject");

        stu_AL_main.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_main.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Science For Technology (SFT)" }));
        stu_AL_main.setBorder(null);
        stu_AL_main.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(153, 153, 153));
        jLabel26.setText("--------A/L Subjects--------");

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 153, 153));
        jLabel28.setText("--------STUDENT DATA--------");

        jLabel29.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel29.setText("First Subject");

        stu_AL_first.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_first.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Engineering Technology (ET)", "Bio Systems Technology (BST)" }));
        stu_AL_first.setBorder(null);
        stu_AL_first.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel30.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel30.setText("Secound Subject");

        stu_AL_secound.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_AL_secound.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "Information And Communication Technology (ICT)", "Agro Technology" }));
        stu_AL_secound.setBorder(null);
        stu_AL_secound.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 153, 153));
        jLabel31.setText("--------O/L Subjects & Results--------");

        jLabel32.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel32.setText("Mathematics : ");

        stu_OL_Mathematics.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Mathematics.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Mathematics.setBorder(null);
        stu_OL_Mathematics.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stu_OL_Mathematics.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                stu_OL_MathematicsItemStateChanged(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel33.setText("Science :");

        stu_OL_Science.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Science.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Science.setBorder(null);
        stu_OL_Science.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        stu_OL_Science.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_OL_ScienceActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel34.setText("Sinhala : ");

        stu_OL_Sinhala.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Sinhala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Sinhala.setBorder(null);
        stu_OL_Sinhala.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel35.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel35.setText("Religion : ");

        stu_OL_Religion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_Religion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_Religion.setBorder(null);
        stu_OL_Religion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel36.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel36.setText("History : ");

        stu_OL_History.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_History.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_History.setBorder(null);
        stu_OL_History.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel37.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel37.setText("English : ");

        stu_OL_English.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_English.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_English.setBorder(null);
        stu_OL_English.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bkt1_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt1_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket I", "Tamil Language", "Geography", "Commerce", "Citizenship Education" }));
        bkt1_name.setBorder(null);
        bkt1_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bkt1_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkt1_nameActionPerformed(evt);
            }
        });

        stu_OL_BKT1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT1.setBorder(null);
        stu_OL_BKT1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bkt2_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt2_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket II", "Eastern music", "Western Music", "Western Music", "Art", "Dancing", "English Language & Literature", "Drama Theater", "Japanese", "Sinhala Literature" }));
        bkt2_name.setBorder(null);
        bkt2_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_BKT2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT2.setBorder(null);
        stu_OL_BKT2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        bkt3_name.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bkt3_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bucket III", "Information &  Communication Technology", "Agriculture", "Health & Physical Education", "Home science", "Media Studies", "Design Technology" }));
        bkt3_name.setBorder(null);
        bkt3_name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        stu_OL_BKT3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        stu_OL_BKT3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT", "A  -  pass", "B  -  pass", "C  -  pass", "S  -  pass", "W -  faild" }));
        stu_OL_BKT3.setBorder(null);
        stu_OL_BKT3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton5.setText("SAVE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton6.setText("CLEAR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButton7.setText("SEARCH");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel23))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(stu_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(stu_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel25))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(stu_AL_main, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(stu_AL_first, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addComponent(jLabel30)
                                                .addGap(18, 18, 18)
                                                .addComponent(stu_AL_secound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel31)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stu_OL_Science, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_OL_Mathematics, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_OL_Sinhala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_OL_Religion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_OL_History, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stu_OL_English, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton5)
                        .addGap(66, 66, 66)
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(bkt3_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(stu_OL_BKT3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bkt2_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bkt1_name, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(stu_OL_BKT2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stu_OL_BKT1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel28)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jLabel31))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(stu_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(stu_AL_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(stu_AL_first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(stu_AL_secound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(stu_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(stu_OL_Mathematics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(stu_OL_Science, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stu_OL_Sinhala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stu_OL_Religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stu_OL_History, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(stu_OL_English, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel35)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel37)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stu_OL_BKT1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bkt1_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bkt2_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stu_OL_BKT2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stu_OL_BKT3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkt3_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Data Insert Menu", jPanel5);

        jTabbedPane1.addTab("Add Data", jTabbedPane4);
        jTabbedPane1.addTab("View Data", jTabbedPane2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Secound Subject", "Third Subject"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("Data Table", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        try {
            lblLink.setEnabled(true);
            lblPort.setEnabled(true);
            lblUser.setEnabled(true);
            lblPassword.setEnabled(true);
            btnStart.setEnabled(true);
            btnStart1.setEnabled(true);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jButton7.setEnabled(false); 
            lblStatus.setText("Scaning...");



            lblStatus.setText("Server Stoped!");
        } catch (Exception e) {
            lblStatus.setText("ERROR : " + e);
            JOptionPane.showMessageDialog(null, "Error: " + e, "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnStopActionPerformed

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        try {
//            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            
            lblLink.setEnabled(false);
            lblPort.setEnabled(false);
            lblUser.setEnabled(false);
            lblPassword.setEnabled(false);
            btnStart.setEnabled(false);
            btnStart1.setEnabled(false);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true); 
            btnStop.setEnabled(true); 
            String url = lblLink.getText() + ":" + lblPort.getText() + "/rcc";
            String user = lblUser.getText();
            String password = lblPassword.getText();
            
            String query = "SELECT * FROM stu_data";
//            String query = "SELECT * FROM stu_data WARE ID = '1'";
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection connection = DriverManager.getConnection(url, user, password);
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(query);
            
            String id;
            String name;
            String f_sub;
            String s_sub;
            String t_sub;
            String line;
            
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            while(result.next()){
                id = result.getString(1);
                name = result.getString(2);
                f_sub = result.getString(3);
                s_sub = result.getString(4);
                t_sub = result.getString(5);


                
                Object[] rowData = {id, name, f_sub, s_sub, t_sub};
                rowData = new Object[]{id, name, f_sub, s_sub, t_sub};
                model.addRow(rowData);
                
            }


                lblStatus.setText("Server Started!");
            } catch (Exception e) {
                lblStatus.setText("ERROR : " + e);
                JOptionPane.showMessageDialog(null, "Error: " + e, "Error", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        lblStatus.setText("Scaning...");
        String url = lblLink.getText() + ":" + lblPort.getText() + "/";
        String user = lblUser.getText();
        String password = lblPassword.getText();
        Connection conn = null;
        try {

            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(url, user, password);
            lblStatus.setText("Connection successful!");
            //            System.out.println("Connection successful!");
        } catch (Exception e) {
            lblStatus.setText("Connection failed!");
            //            System.err.println("Connection failed!");
            //            e.printStackTrace();
        } finally {
            try {
                conn.close();
            } catch (SQLException e) {
                lblStatus.setText("ERROR : " + e);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void stu_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_IDActionPerformed

    private void stu_OL_MathematicsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_stu_OL_MathematicsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_OL_MathematicsItemStateChanged

    private void bkt1_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkt1_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bkt1_nameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String url = lblLink.getText() + ":" + lblPort.getText() + "/rcc";
        String user = lblUser.getText();
        String password = lblPassword.getText();
        
        
        String ID = stu_ID.getText();
        try {
            int num = Integer.parseInt(ID);
        } catch (Exception e) {
        }
        
        String name = stu_Name.getText();
        String m_sub = stu_AL_main.getSelectedItem().toString();
        String f_sub = stu_AL_first.getSelectedItem().toString();
        String s_sub = stu_AL_secound.getSelectedItem().toString();
        String ol_maths = stu_OL_Mathematics.getSelectedItem().toString();
        String ol_science = stu_OL_Science.getSelectedItem().toString();
        String ol_sinhala = stu_OL_Sinhala.getSelectedItem().toString();
        String ol_religion = stu_OL_Religion.getSelectedItem().toString();
        String ol_history = stu_OL_History.getSelectedItem().toString();
        String ol_english = stu_OL_English.getSelectedItem().toString();
        String part_1 = bkt1_name.getSelectedItem().toString();
        String ol_part1 = stu_OL_BKT1.getSelectedItem().toString();
        String part_2 = bkt2_name.getSelectedItem().toString();
        String ol_part2 = stu_OL_BKT2.getSelectedItem().toString();
        String part_3 = bkt3_name.getSelectedItem().toString();
        String ol_part3 = stu_OL_BKT3.getSelectedItem().toString();
        try {
            if(name == "" && ID == ""){
                JOptionPane.showMessageDialog(null,"Check Name And ID");
            }
            else{
                String query = "INSERT INTO stu_data VALUES ("+ ID +",'"+ name +"', '"+ m_sub +"', '"+ f_sub +"', '"+ s_sub +"', '"+ ol_maths +"', '"+ ol_science +"', '"+ ol_sinhala +"', '"+ ol_religion +"', '"+ ol_english +"', '"+ part_1 +"', '"+ ol_part1 +"', '"+ part_2 +"', '"+ ol_part2 +"', '"+ part_3 +"', '"+ ol_part3 +"', '"+ ol_history +"')"; //ol_history
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection connection = DriverManager.getConnection(url, user, password);
                Statement statement = connection.createStatement();
                        
                statement.executeUpdate(query);
                stu_ID.setText("");
                stu_Name.setText("");
                stu_AL_main.setSelectedIndex(0);
                stu_AL_first.setSelectedIndex(0);
                stu_AL_secound.setSelectedIndex(0);
                stu_OL_Mathematics.setSelectedIndex(0);
                stu_OL_Science.setSelectedIndex(0);
                stu_OL_Sinhala.setSelectedIndex(0);
                stu_OL_Religion.setSelectedIndex(0);
                stu_OL_History.setSelectedIndex(0);
                stu_OL_English.setSelectedIndex(0);
                bkt1_name.setSelectedIndex(0);   
                stu_OL_BKT1.setSelectedIndex(0);  
                bkt2_name.setSelectedIndex(0);
                stu_OL_BKT2.setSelectedIndex(0);
                bkt3_name.setSelectedIndex(0);        
                stu_OL_BKT3.setSelectedIndex(0);        
                stu_OL_BKT1.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"ERROR : " + e);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        stu_ID.setText("");
        stu_Name.setText("");
        stu_AL_main.setSelectedIndex(0);
        stu_AL_first.setSelectedIndex(0);
        stu_AL_secound.setSelectedIndex(0);
        stu_OL_Mathematics.setSelectedIndex(0);
        stu_OL_Science.setSelectedIndex(0);
        stu_OL_Sinhala.setSelectedIndex(0);
        stu_OL_Religion.setSelectedIndex(0);
        stu_OL_History.setSelectedIndex(0);
        stu_OL_English.setSelectedIndex(0);
        bkt1_name.setSelectedIndex(0);   
        stu_OL_BKT1.setSelectedIndex(0);  
        bkt2_name.setSelectedIndex(0);
        stu_OL_BKT2.setSelectedIndex(0);
        bkt3_name.setSelectedIndex(0);        
        stu_OL_BKT3.setSelectedIndex(0);        
        stu_OL_BKT1.setSelectedIndex(0);
        jButton5.setText("SAVE");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String url = lblLink.getText() + ":" + lblPort.getText() + "/rcc";
        String user = lblUser.getText();
        String password = lblPassword.getText();
        
        if (stu_ID.getText() != ""){
            try {
                String i_d =  stu_ID.getText();
                int id = Integer.parseInt(i_d);

                Connection con = DriverManager.getConnection(url, user, password);
                String query = "SELECT * FROM stu_data WHERE id = ?";
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setInt(1, id); // set the value of the first parameter to 1
                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    System.out.println("ID: " + rs.getInt("ID"));
                    System.out.println("Name: " + rs.getString("name"));
    //                System.out.println("Age: " + rs.getInt("age"));
                } else {
//                    System.out.println("No rows found!");
                    JOptionPane.showMessageDialog(null,"No rows found!");
                }
                con.close();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            jButton5.setText("EDIT");
        }
        else{
            JOptionPane.showMessageDialog(null,"Check ID value");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void stu_OL_ScienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_OL_ScienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stu_OL_ScienceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bkt1_name;
    private javax.swing.JComboBox<String> bkt2_name;
    private javax.swing.JComboBox<String> bkt3_name;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStart1;
    private javax.swing.JButton btnStop;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lblLink;
    private javax.swing.JPasswordField lblPassword;
    private javax.swing.JTextField lblPort;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField lblUser;
    private javax.swing.JComboBox<String> stu_AL_first;
    private javax.swing.JComboBox<String> stu_AL_main;
    private javax.swing.JComboBox<String> stu_AL_secound;
    private javax.swing.JTextField stu_ID;
    private javax.swing.JTextField stu_Name;
    private javax.swing.JComboBox<String> stu_OL_BKT1;
    private javax.swing.JComboBox<String> stu_OL_BKT2;
    private javax.swing.JComboBox<String> stu_OL_BKT3;
    private javax.swing.JComboBox<String> stu_OL_English;
    private javax.swing.JComboBox<String> stu_OL_History;
    private javax.swing.JComboBox<String> stu_OL_Mathematics;
    private javax.swing.JComboBox<String> stu_OL_Religion;
    private javax.swing.JComboBox<String> stu_OL_Science;
    private javax.swing.JComboBox<String> stu_OL_Sinhala;
    // End of variables declaration//GEN-END:variables
}
